/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Vote } from "./Vote";
import { VoteCountArgs } from "./VoteCountArgs";
import { VoteFindManyArgs } from "./VoteFindManyArgs";
import { VoteFindUniqueArgs } from "./VoteFindUniqueArgs";
import { CreateVoteArgs } from "./CreateVoteArgs";
import { UpdateVoteArgs } from "./UpdateVoteArgs";
import { DeleteVoteArgs } from "./DeleteVoteArgs";
import { Poll } from "../../poll/base/Poll";
import { VoteService } from "../vote.service";
@graphql.Resolver(() => Vote)
export class VoteResolverBase {
  constructor(protected readonly service: VoteService) {}

  async _votesMeta(
    @graphql.Args() args: VoteCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Vote])
  async votes(@graphql.Args() args: VoteFindManyArgs): Promise<Vote[]> {
    return this.service.votes(args);
  }

  @graphql.Query(() => Vote, { nullable: true })
  async vote(@graphql.Args() args: VoteFindUniqueArgs): Promise<Vote | null> {
    const result = await this.service.vote(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Vote)
  async createVote(@graphql.Args() args: CreateVoteArgs): Promise<Vote> {
    return await this.service.createVote({
      ...args,
      data: {
        ...args.data,

        poll: args.data.poll
          ? {
              connect: args.data.poll,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Vote)
  async updateVote(@graphql.Args() args: UpdateVoteArgs): Promise<Vote | null> {
    try {
      return await this.service.updateVote({
        ...args,
        data: {
          ...args.data,

          poll: args.data.poll
            ? {
                connect: args.data.poll,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Vote)
  async deleteVote(@graphql.Args() args: DeleteVoteArgs): Promise<Vote | null> {
    try {
      return await this.service.deleteVote(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Poll, {
    nullable: true,
    name: "poll",
  })
  async getPoll(@graphql.Parent() parent: Vote): Promise<Poll | null> {
    const result = await this.service.getPoll(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
