/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CheckInCreateNestedManyWithoutEventsInput } from "./CheckInCreateNestedManyWithoutEventsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsDate,
  IsNumber,
} from "class-validator";
import { Type } from "class-transformer";
import { TicketCreateNestedManyWithoutEventsInput } from "./TicketCreateNestedManyWithoutEventsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class EventCreateInput {
  @ApiProperty({
    required: false,
    type: () => CheckInCreateNestedManyWithoutEventsInput,
  })
  @ValidateNested()
  @Type(() => CheckInCreateNestedManyWithoutEventsInput)
  @IsOptional()
  @Field(() => CheckInCreateNestedManyWithoutEventsInput, {
    nullable: true,
  })
  checkIns?: CheckInCreateNestedManyWithoutEventsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endTime?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startTime?: Date | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  ticketPrice?: number | null;

  @ApiProperty({
    required: false,
    type: () => TicketCreateNestedManyWithoutEventsInput,
  })
  @ValidateNested()
  @Type(() => TicketCreateNestedManyWithoutEventsInput)
  @IsOptional()
  @Field(() => TicketCreateNestedManyWithoutEventsInput, {
    nullable: true,
  })
  tickets?: TicketCreateNestedManyWithoutEventsInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  tieredPrices?: InputJsonValue;
}

export { EventCreateInput as EventCreateInput };
